name: CI/CD for Containerized Architecture

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_RESOURCE_GROUP: rg-traffic-sign-detector-prod
  AZURE_CONTAINER_REGISTRY: acrtrafficsignprod
  AZURE_CONTAINER_APPS_ENVIRONMENT: whitestone-e7e06cfe
  AZURE_BACKEND_CONTAINER_APP: backend-traffic-prod
  AZURE_FRONTEND_CONTAINER_APP: frontend-traffic-prod
  POSTGRESQL_SERVER_NAME: psql-traffic-sign-prod-new
  POSTGRESQL_DATABASE_NAME: traffic_sign_detector
  REDIS_CACHE_NAME: redis-traffic-sign-detector-prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push production Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-app:${{ github.sha }}
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-app:latest

  deploy-app:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update Backend Container App (Full Stack)
      run: |
        az containerapp update \
          --name ${{ env.AZURE_BACKEND_CONTAINER_APP }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-app:latest

    - name: Scale Down Frontend Container App
      run: |
        az containerapp update \
          --name ${{ env.AZURE_FRONTEND_CONTAINER_APP }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --min-replicas 0 \
          --max-replicas 0
