name: CI/CD for Containerized Architecture

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_RESOURCE_GROUP: rg-traffic-sign-detector-prod
  AZURE_CONTAINER_REGISTRY: acrtrafficsignprod
  AZURE_CONTAINER_APPS_ENVIRONMENT: cae-traffic-sign-detector-prod
  AZURE_BACKEND_CONTAINER_APP: backend-traffic-prod
  AZURE_FRONTEND_CONTAINER_APP: frontend-traffic-prod
  POSTGRESQL_SERVER_NAME: psql-traffic-sign-prod-new
  POSTGRESQL_DATABASE_NAME: traffic_sign_db
  REDIS_CACHE_NAME: redis-traffic-sign-detector-prod
  LOCATION: eastus

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./Dockerfile.backend
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-backend:${{ github.sha }}
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./Dockerfile.frontend
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-frontend:${{ github.sha }}
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push-backend, build-and-push-frontend]
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Backend Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: ${{ env.AZURE_BACKEND_CONTAINER_APP }}
        resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
        image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-backend:latest
        environmentVariables: |
          DATABASE_URL=postgresql://${{ secrets.DB_ADMIN_USERNAME }}:${{ secrets.DB_ADMIN_PASSWORD }}@${{ env.POSTGRESQL_SERVER_NAME }}.postgres.database.azure.com:5432/${{ env.POSTGRESQL_DATABASE_NAME }}?sslmode=require
          REDIS_URL=rediss://:${{ secrets.REDIS_PASSWORD }}@${{ env.REDIS_CACHE_NAME }}.redis.cache.windows.net:6380
          SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG=False
          ALLOWED_HOSTS=*

    - name: Deploy Frontend Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        containerAppName: ${{ env.AZURE_FRONTEND_CONTAINER_APP }}
        resourceGroup: ${{ env.AZURE_RESOURCE_GROUP }}
        image: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/traffic-sign-frontend:latest
        environmentVariables: |
          REACT_APP_API_URL=https://${{ env.AZURE_BACKEND_CONTAINER_APP }}.azurecontainerapps.io

    - name: Run Django Migrations
      run: |
        echo "Manual step: Run Django migrations on the backend container."
        echo "You would typically do this via a startup script in your backend Dockerfile or a separate job."
        echo "Example if using Azure CLI to run a command:"
        echo "az containerapp exec -n ${{ env.AZURE_BACKEND_CONTAINER_APP }} -g ${{ env.AZURE_RESOURCE_GROUP }} --command 'python manage.py migrate'"
